<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="King" name="TestCases.P2P_TBJ_Mobile_SeriesB" tests="54" failures="0" timestamp="20 Sep 2017 03:17:32 GMT" time="61.192" errors="54">
  <testcase name="case_45" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_45(P2P_TBJ_Mobile_SeriesB.java:306)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 17 more
]]>
    </error>
  </testcase> <!-- case_45 -->
  <testcase name="case_27" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:50)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_27(P2P_TBJ_Mobile_SeriesB.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case_27 -->
  <testcase name="case_20" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_20(P2P_TBJ_Mobile_SeriesB.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_20 -->
  <testcase name="case_34" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_34(P2P_TBJ_Mobile_SeriesB.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_34 -->
  <testcase name="case1" time="0.007" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case1(P2P_TBJ_Mobile_SeriesB.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.handler.SlideAction_Handler.commonSlide(SlideAction_Handler.java:185)
	at com.dafycredit.giveu.test.handler.SlideAction_Handler.slideLeft(SlideAction_Handler.java:40)
	... 18 more
]]>
    </error>
  </testcase> <!-- case1 -->
  <testcase name="case_16" time="0.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_16(P2P_TBJ_Mobile_SeriesB.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_16 -->
  <testcase name="case_14" time="0.072" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_14(P2P_TBJ_Mobile_SeriesB.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.handler.DBAction_Handler.dbQuery(DBAction_Handler.java:54)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_14 -->
  <testcase name="case_50" time="60.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_50(P2P_TBJ_Mobile_SeriesB.java:336)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.handler.SlideAction_Handler.commonSlide(SlideAction_Handler.java:185)
	at com.dafycredit.giveu.test.handler.SlideAction_Handler.slideDown(SlideAction_Handler.java:92)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_50 -->
  <testcase name="case_33" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_33(P2P_TBJ_Mobile_SeriesB.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_33 -->
  <testcase name="case_41" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_41(P2P_TBJ_Mobile_SeriesB.java:282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.handler.SlideAction_Handler.commonSlide(SlideAction_Handler.java:210)
	at com.dafycredit.giveu.test.handler.SlideAction_Handler.slide(SlideAction_Handler.java:107)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_41 -->
  <testcase name="case_26" time="0.004" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_26(P2P_TBJ_Mobile_SeriesB.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_26 -->
  <testcase name="case_36" time="0.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_36(P2P_TBJ_Mobile_SeriesB.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_36 -->
  <testcase name="case_43" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_43(P2P_TBJ_Mobile_SeriesB.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.handler.SlideAction_Handler.commonSlide(SlideAction_Handler.java:185)
	at com.dafycredit.giveu.test.handler.SlideAction_Handler.slideUp(SlideAction_Handler.java:74)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_43 -->
  <testcase name="case_28" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_28(P2P_TBJ_Mobile_SeriesB.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_28 -->
  <testcase name="case_32" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_32(P2P_TBJ_Mobile_SeriesB.java:228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_32 -->
  <testcase name="case_46" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:50)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_46(P2P_TBJ_Mobile_SeriesB.java:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case_46 -->
  <testcase name="case_15" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_15(P2P_TBJ_Mobile_SeriesB.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_15 -->
  <testcase name="case_18" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_18(P2P_TBJ_Mobile_SeriesB.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_18 -->
  <testcase name="case_21" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_21(P2P_TBJ_Mobile_SeriesB.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case_21 -->
  <testcase name="case_38" time="0.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_38(P2P_TBJ_Mobile_SeriesB.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_38 -->
  <testcase name="case7" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case7(P2P_TBJ_Mobile_SeriesB.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case7 -->
  <testcase name="case_13" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:50)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_13(P2P_TBJ_Mobile_SeriesB.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case_13 -->
  <testcase name="case_29" time="0.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_29(P2P_TBJ_Mobile_SeriesB.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_29 -->
  <testcase name="case_30" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$2.run(Step_Action.java:40)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_30(P2P_TBJ_Mobile_SeriesB.java:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case_30 -->
  <testcase name="case_17" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_17(P2P_TBJ_Mobile_SeriesB.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_17 -->
  <testcase name="case5" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case5(P2P_TBJ_Mobile_SeriesB.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case5 -->
  <testcase name="case3" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case3(P2P_TBJ_Mobile_SeriesB.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case3 -->
  <testcase name="case_10" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_10(P2P_TBJ_Mobile_SeriesB.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_10 -->
  <testcase name="case4" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:50)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case4(P2P_TBJ_Mobile_SeriesB.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case4 -->
  <testcase name="Precondition" time="1.055" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.Precondition(P2P_TBJ_Mobile_SeriesB.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.handler.DBAction_Handler.dbUpdate(DBAction_Handler.java:42)
	... 18 more
]]>
    </error>
  </testcase> <!-- Precondition -->
  <testcase name="case_19" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_19(P2P_TBJ_Mobile_SeriesB.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_19 -->
  <testcase name="case2" time="0.006" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case2(P2P_TBJ_Mobile_SeriesB.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case2 -->
  <testcase name="case_49" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_49(P2P_TBJ_Mobile_SeriesB.java:330)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 17 more
]]>
    </error>
  </testcase> <!-- case_49 -->
  <testcase name="case_51" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.base.Step_Action$8.run(Step_Action.java:100)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_51(P2P_TBJ_Mobile_SeriesB.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case_51 -->
  <testcase name="case_44" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.base.Step_Action$8.run(Step_Action.java:100)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_44(P2P_TBJ_Mobile_SeriesB.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case_44 -->
  <testcase name="case_52" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_52(P2P_TBJ_Mobile_SeriesB.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.parseStringHasEls(Appium_Util.java:119)
	at com.dafycredit.giveu.test.handler.DBAction_Handler.dbProcedure(DBAction_Handler.java:58)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_52 -->
  <testcase name="case_22" time="0.012" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_22(P2P_TBJ_Mobile_SeriesB.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case_22 -->
  <testcase name="case_47" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_47(P2P_TBJ_Mobile_SeriesB.java:318)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 17 more
]]>
    </error>
  </testcase> <!-- case_47 -->
  <testcase name="case_31" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_31(P2P_TBJ_Mobile_SeriesB.java:222)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_31 -->
  <testcase name="case_23" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_23(P2P_TBJ_Mobile_SeriesB.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_23 -->
  <testcase name="case_53" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_53(P2P_TBJ_Mobile_SeriesB.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.parseStringHasEls(Appium_Util.java:119)
	at com.dafycredit.giveu.test.handler.DBAction_Handler.dbQuery(DBAction_Handler.java:48)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_53 -->
  <testcase name="case_35" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.base.Step_Action$8.run(Step_Action.java:100)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_35(P2P_TBJ_Mobile_SeriesB.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case_35 -->
  <testcase name="case_37" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.base.Step_Action$8.run(Step_Action.java:100)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_37(P2P_TBJ_Mobile_SeriesB.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case_37 -->
  <testcase name="case9" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case9(P2P_TBJ_Mobile_SeriesB.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case9 -->
  <testcase name="case_25" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_25(P2P_TBJ_Mobile_SeriesB.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_25 -->
  <testcase name="case_24" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_24(P2P_TBJ_Mobile_SeriesB.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_24 -->
  <testcase name="case_12" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_12(P2P_TBJ_Mobile_SeriesB.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_12 -->
  <testcase name="case_40" time="0.002" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_40(P2P_TBJ_Mobile_SeriesB.java:276)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_40 -->
  <testcase name="case_42" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_42(P2P_TBJ_Mobile_SeriesB.java:288)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_42 -->
  <testcase name="case_39" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_39(P2P_TBJ_Mobile_SeriesB.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_39 -->
  <testcase name="case6" time="0.001" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:50)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case6(P2P_TBJ_Mobile_SeriesB.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case6 -->
  <testcase name="case8" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.base.Step_Action$6.run(Step_Action.java:77)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:100)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case8(P2P_TBJ_Mobile_SeriesB.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- case8 -->
  <testcase name="case_11" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_11(P2P_TBJ_Mobile_SeriesB.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:27)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_11 -->
  <testcase name="case_48" time="0.000" classname="TestCases.P2P_TBJ_Mobile_SeriesB">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:98)
	at TestCases.P2P_TBJ_Mobile_SeriesB.case_48(P2P_TBJ_Mobile_SeriesB.java:324)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:73)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:34)
	... 18 more
]]>
    </error>
  </testcase> <!-- case_48 -->
</testsuite> <!-- TestCases.P2P_TBJ_Mobile_SeriesB -->
