<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="King" name="JYBTestCases.P2P_DR_Mobile_SeriesA" tests="1" failures="0" timestamp="17 Nov 2017 07:43:47 GMT" time="1.702" errors="1">
  <testcase name="Precondition" time="1.702" classname="JYBTestCases.P2P_DR_Mobile_SeriesA">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:86)
	at JYBTestCases.P2P_DR_Mobile_SeriesA.Precondition(P2P_DR_Mobile_SeriesA.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.dafycredit.giveu.test.handler.DBAction_Handler.dbUpdate(DBAction_Handler.java:56)
	... 18 more
]]>
    </error>
  </testcase> <!-- Precondition -->
</testsuite> <!-- JYBTestCases.P2P_DR_Mobile_SeriesA -->
